Set max width to account for period
mcode/clinical-trial-matching-app pull request #30
Opened 2022-03-10 21:49 UTC by ChristineDuong

Accompanies this PR: https://github.com/mcode/clinical-trial-matching-service/pull/29

Now that the period is available, this change just ensures that the part of the `StudyHeader` that has the period is not variable and will not extend past a certain width.

2022-03-11 21:02 UTC, jtquach1 requested changes

2022-03-11 21:13 UTC, ChristineDuong commented on src/components/Results/StudyHeader.tsx
> +            style={{ maxWidth: 160 }}
![Screen Shot 2022-03-11 at 4 09 37 PM](https://user-images.githubusercontent.com/6525651/157967238-f7cac92b-2aba-462f-bc2b-b6f8f144ebbb.png)

I made the changes that you requested, but for me the space is rather large. I have no issue with this, but that is why I originally set the maxwidth as I thought the space was sufficient.

2022-03-11 22:12 UTC, jtquach1 commented on src/components/Results/StudyHeader.tsx
> +            style={{ maxWidth: 160 }}
Testing out some of the different options for flexbox styling (flex-grow and flex-shrink) on a 2560x1600 screen (in DevTools) for the Stack containing the likelihood/distance/period info:
### flex: "5 4"
![image](https://user-images.githubusercontent.com/33106214/157974530-585b1a10-7c5e-4bab-921a-4cb00abcf8ea.png)

### flex: "6 4"
![image](https://user-images.githubusercontent.com/33106214/157974535-6de9461c-c32a-4853-a238-c6982ececd2b.png)

### flex: "7 4"
![image](https://user-images.githubusercontent.com/33106214/157974551-69ed41a2-728f-41b9-b6fa-3bcf6aeecc50.png)

### flex: "8 4"
![image](https://user-images.githubusercontent.com/33106214/157974569-e6d7c86d-3110-4b4b-83b6-295d1ccb8703.png)

### flex: "9 4"
![image](https://user-images.githubusercontent.com/33106214/157974583-53e1e98e-3f24-47cf-8269-e3cc31b98773.png)

### flex: "10 4"
![image](https://user-images.githubusercontent.com/33106214/157974594-ea0eaef4-0560-47ea-a0ff-75ace84efc17.png)

2022-03-14 17:08 UTC, jtquach1 approved these changes

2022-03-15 15:45 UTC, merged