Flesh out Results view UI
mcode/clinical-trial-matching-app pull request #8
Opened 2021-10-20 01:17 UTC by jtquach1

This PR provides the basic structure of the results view including listing resulting studies. Much of the data is still hard coded and notated with `TODO` comments. This also uses mock results data which will be hooked up at a later time.

2021-11-17 03:37 UTC, noranda commented
@jtquach1 and @dmpotter44: This PR has been updated and is ready for review.

2021-11-17 16:54 UTC, jtquach1 commented
The results view looks squashed on xs screens; e.g. Pixel XL (although arguably one could just rotate the phone to get the sm screen size). 
![image](https://user-images.githubusercontent.com/33106214/142244598-0c7c3a37-1cae-413c-a9a1-bbbffe01c8d1.png)

Maybe the study status box ("closed to accrual") could become 12-columns wide on xs screens?

Besides that, I think everything looks good to me. I'll flesh out `getDistance` and `getClosestFacility` in #10 .

2021-11-18 03:25 UTC, noranda commented
> The results view looks squashed on xs screens

Fixed the responsive layout of the sidebar to help with this. Take a look and let me know what you think!

2021-11-18 18:49 UTC, noranda commented on src/components/Results/StudyHeader.tsx
> +  );
Pushed up a commit to resolve this. Decided to keep the status as a small tag on the top left when at very small widths. Let me know what you think!

<img width="424" alt="Screen Shot 2021-11-18 at 1 45 52 PM" src="https://user-images.githubusercontent.com/5418735/142477994-7caeeff4-3c48-44bd-bd3a-899a527f7424.png">

2021-11-18 19:12 UTC, jtquach1 commented
This looks good to me! I didn't know about AccordionActions, that's really nifty.

2021-11-18 20:06 UTC, jtquach1 commented
> This looks good to me! I didn't know about AccordionActions, that's really nifty.

My bad, I missed this earlier- on xs screens (iPhone 5 size) there's a bit of clipping: 
![image](https://user-images.githubusercontent.com/33106214/142488544-f6befb2b-7786-4319-9e03-ca8004e6ab6f.png)

I think that can be resolved with changing the base font size for xs screens, but also the menu hamburger icon/touch area is cut off on screens <400px wide.
![image](https://user-images.githubusercontent.com/33106214/142488759-dac23488-f7ff-4c6f-ba35-41969be9d512.png)

I can take a stab at these two issues since I have time for the end of this week.

2021-11-23 03:37 UTC, jtquach1 commented
# Screenshots of current visual changes:
| xs screen (Pixel 2)  | sm screen (Surface Duo) | md screen (iPad) | lg screen (iPad Pro) | xl screen (MacBook Pro) | Sidebar on xs screen (Galaxy Fold, Pixel 2) | Sidebar on non-xs screen (Surface Duo, iPad) |
| - | - | - | - | - | - | - |
| ![image](https://user-images.githubusercontent.com/33106214/142966700-323565c1-f419-41b0-8fa9-5530b0f36279.png)  | ![image](https://user-images.githubusercontent.com/33106214/142966739-5bda8ac1-6569-40df-bbea-84bb22fe5437.png) | ![image](https://user-images.githubusercontent.com/33106214/142966775-d5a94bec-619e-492a-aaa2-4499d886431a.png) | ![image](https://user-images.githubusercontent.com/33106214/142966864-9db8c30b-cbed-48da-808d-563066a23d52.png) | ![image](https://user-images.githubusercontent.com/33106214/142966947-73317781-5303-493a-b52d-74d3b59567c8.png) | ![image](https://user-images.githubusercontent.com/33106214/142967599-31bb9e99-13d4-4c2b-a6b5-43c403c6a76d.png) | ![image](https://user-images.githubusercontent.com/33106214/142967715-e0dadc6b-ebd8-4976-b19f-98346e0928d4.png) |
| ![image](https://user-images.githubusercontent.com/33106214/142966713-f2b8bfe1-31bb-41a0-8791-24cfd73e56db.png)  | ![image](https://user-images.githubusercontent.com/33106214/142966752-893e06f4-7d78-4918-a3e7-0fc0f90e25d7.png)  | ![image](https://user-images.githubusercontent.com/33106214/142966829-a05a98a4-8d6e-4286-92a0-2f9e1eb424a6.png) | ![image](https://user-images.githubusercontent.com/33106214/142967098-2632f7d3-3e86-4941-952c-bad17f848b1f.png) | ![image](https://user-images.githubusercontent.com/33106214/142966967-e2658077-81b8-4ff4-a107-507c242ac26a.png) | ![image](https://user-images.githubusercontent.com/33106214/142967628-260bdbaf-8347-4f78-b497-e8621e461083.png) | ![image](https://user-images.githubusercontent.com/33106214/142967742-bceacfc7-df43-4dfb-9044-ec6e7f263c3a.png) |

2021-12-01 19:59 UTC, noranda requested changes
This is looking very good! Nice job on improving the responsiveness. The only thing I think we need to fix is the following console warning: `Warning: Received `false` for a non-boolean attribute `shrink`.` when the results first render (tested on iPhone X). Otherwise all lint and tests pass and app works as expected.

2021-12-02 00:21 UTC, jtquach1 commented
> This is looking very good! Nice job on improving the responsiveness. The only thing I think we need to fix is the following console warning: `` Warning: Received `false` for a non-boolean attribute `shrink`. `` when the results first render (tested on iPhone X). Otherwise all lint and tests pass and app works as expected.

Thanks for catching that! The error seems to have disappeared upon checking `shrink` as one of the props to not forward to the DOM (latest commit).

2021-12-02 17:34 UTC, merged